export const translations = {
  en: {
    appName: "SiteAuditPro",
    tagline: "Master Your SEO & Skyrocket Your Traffic",
    description: "Get the same insights as top SEO experts. Analyze any website and get a step-by-step plan to dominate search results.",
    heroTag: "AI-POWERED ANALYSIS",
    heroCTA: "Start Free Audit",
    placeholder: "Enter website URL (e.g., example.com)",
    analyzeBtn: "Analyze",
    loading: "This usually takes about 30-60 seconds...",
    features: "Features",
    pricing: "Pricing",
    resources: "Resources",
    about: "About Us",
    contact: "Contact",
    home: "Home",
    resultsTitle: "Detailed Audit Report",
    generatedOn: "Generated on",
    readyToImplement: "Ready to implement these changes?",
    expertsHelp: "Our experts can help you optimize your site for maximum performance.",
    getStarted: "Get Started Now",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contactUs: "Contact Us",
    allRightsReserved: "All rights reserved.",
    analysisFailed: "Analysis Failed",
    tryAgain: "Try again",
    uxDesign: "UX & Design",
    seoScore: "SEO Score",
    performance: "Performance",
    conversion: "Conversion",
    professional: "Professional",
    optimized: "Optimized",
    fast: "Fast",
    highPotential: "High Potential",
    plansTitle: "Choose Your Plan",
    plansSubtitle: "Scale your website optimization with the right tools.",
    free: "Free",
    pro: "Pro",
    enterprise: "Enterprise",
    monthly: "/mo",
    selectPlan: "Select Plan",
    aboutTitle: "About SiteAudit Pro",
    aboutText: "We are a team of SEO and UX enthusiasts dedicated to helping website owners improve their digital presence through AI-powered insights.",
    contactTitle: "Contact Us",
    contactSubtitle: "Have questions? We're here to help.",
    nameLabel: "Name",
    emailLabel: "Email",
    messageLabel: "Message",
    sendBtn: "Send Message",
    scoresTitle: "Performance Overview",
    billingMonthly: "Monthly",
    billingAnnual: "Annual (Save 10%)",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    googleSignIn: "Continue with Google",
    githubSignIn: "Continue with GitHub",
    account: "Account",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    emailPlaceholder: "name@example.com",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Forgot password?",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    featuresTitle: "Everything you need to grow",
    annualDiscount: "10% off applied",
  },
  pt: {
    appName: "SiteAuditPro",
    tagline: "Domine seu SEO e Faça seu Tráfego Decolar",
    description: "Obtenha os mesmos insights dos maiores especialistas em SEO. Analise qualquer site e receba um plano passo a passo para dominar os resultados de busca.",
    heroTag: "ANÁLISE COM INTELIGÊNCIA ARTIFICIAL",
    heroCTA: "Iniciar Auditoria Grátis",
    placeholder: "Introduza o URL do site (ex: exemplo.com)",
    analyzeBtn: "Analisar",
    loading: "Isto costuma demorar cerca de 30-60 segundos...",
    features: "Funcionalidades",
    pricing: "Preços",
    resources: "Recursos",
    about: "Sobre Nós",
    contact: "Contacto",
    home: "Início",
    resultsTitle: "Relatório de Auditoria Detalhado",
    generatedOn: "Gerado em",
    readyToImplement: "Pronto para implementar estas mudanças?",
    expertsHelp: "Os nossos especialistas podem ajudá-lo a otimizar o seu site para o máximo desempenho.",
    getStarted: "Começar Agora",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    contactUs: "Contacte-nos",
    allRightsReserved: "Todos os direitos reservados.",
    analysisFailed: "Falha na Análise",
    tryAgain: "Tentar novamente",
    uxDesign: "UX & Design",
    seoScore: "Pontuação SEO",
    performance: "Desempenho",
    conversion: "Conversão",
    professional: "Profissional",
    optimized: "Otimizado",
    fast: "Rápido",
    highPotential: "Alto Potencial",
    plansTitle: "Escolha o Seu Plano",
    plansSubtitle: "Aumente a otimização do seu site com as ferramentas certas.",
    free: "Grátis",
    pro: "Pro",
    enterprise: "Empresarial",
    monthly: "/mês",
    selectPlan: "Selecionar Plano",
    aboutTitle: "Sobre o SiteAudit Pro",
    aboutText: "Somos uma equipa de entusiastas de SEO e UX dedicados a ajudar proprietários de sites a melhorar a sua presença digital através de insights baseados em IA.",
    contactTitle: "Contacte-nos",
    contactSubtitle: "Tem dúvidas? Estamos aqui para ajudar.",
    nameLabel: "Nome",
    emailLabel: "Email",
    messageLabel: "Mensagem",
    sendBtn: "Enviar Mensagem",
    scoresTitle: "Visão Geral de Desempenho",
    billingMonthly: "Mensal",
    billingAnnual: "Anual (Poupe 10%)",
    signIn: "Entrar",
    signUp: "Registar",
    signOut: "Sair",
    googleSignIn: "Continuar com Google",
    githubSignIn: "Continuar com GitHub",
    account: "Minha Conta",
    welcomeBack: "Bem-vindo de volta",
    createAccount: "Crie a sua conta",
    emailPlaceholder: "nome@exemplo.com",
    passwordPlaceholder: "••••••••",
    forgotPassword: "Esqueceu-se da palavra-passe?",
    alreadyHaveAccount: "Já tem uma conta?",
    dontHaveAccount: "Não tem uma conta?",
    featuresTitle: "Tudo o que precisa para crescer",
    annualDiscount: "Desconto de 10% aplicado",
  }
};
